# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install OS dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libsqlite3-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
RUN pip install --no-cache-dir \
    chromadb>=1.0.4 \
    mcp[cli]>=1.6.0 \
    pytube>=15.0.0 \
    youtube-transcript-api>=1.0.3 \
    anyio

# Copy project source
COPY . /app

# Ensure stdout is unbuffered
ENV PYTHONUNBUFFERED=1

# Default entrypoint (args supplied by config)
ENTRYPOINT ["python", "server.py"]
